// Generated by gencpp from file my_robot/ackermann.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MESSAGE_ACKERMANN_H
#define MY_ROBOT_MESSAGE_ACKERMANN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>
#include <std_msgs/Float64.h>

namespace my_robot
{
template <class ContainerAllocator>
struct ackermann_
{
  typedef ackermann_<ContainerAllocator> Type;

  ackermann_()
    : twist()
    , direction()  {
    }
  ackermann_(const ContainerAllocator& _alloc)
    : twist(_alloc)
    , direction(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _twist_type;
  _twist_type twist;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::my_robot::ackermann_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot::ackermann_<ContainerAllocator> const> ConstPtr;

}; // struct ackermann_

typedef ::my_robot::ackermann_<std::allocator<void> > ackermann;

typedef boost::shared_ptr< ::my_robot::ackermann > ackermannPtr;
typedef boost::shared_ptr< ::my_robot::ackermann const> ackermannConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot::ackermann_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot::ackermann_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_robot': ['/home/tran/github/robot_ws/src/my_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_robot::ackermann_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot::ackermann_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot::ackermann_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot::ackermann_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot::ackermann_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot::ackermann_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot::ackermann_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0bbc953f7e50c6c3cf3e95445bab2fd3";
  }

  static const char* value(const ::my_robot::ackermann_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0bbc953f7e50c6c3ULL;
  static const uint64_t static_value2 = 0xcf3e95445bab2fd3ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot::ackermann_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot/ackermann";
  }

  static const char* value(const ::my_robot::ackermann_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot::ackermann_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist twist\n\
std_msgs/Float64 direction\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
";
  }

  static const char* value(const ::my_robot::ackermann_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot::ackermann_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.twist);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ackermann_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot::ackermann_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot::ackermann_<ContainerAllocator>& v)
  {
    s << indent << "twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
    s << indent << "direction: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MESSAGE_ACKERMANN_H
